-- auto Generated on 2017-01-25 14:44:48 
-- DROP TABLE IF EXISTS `tag_po`; 
CREATE TABLE `tag_po`(
    `id` INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `tag_name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'tagName',
    `create_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'createTime',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '`tag_po`';
